macro generate_source(data)
<<-EOT
# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT !

require "../spec_helper"

def it_matches(name)
  it "`\#{name[0]}` (\#{name[3]}) should match `\#{name[2]}` (\#{name[1]})" do
    name[1].match(Emoji::GENERATED_EMOJI_REGEX).try(&.[0]).should eq name[1]
  end
end

{% for name in data %}it_matches({{name}})
{% end %}
EOT
end

macro create_source_file
  source = generate_source({{run("./test_file_loader.cr").id}})
  File.write("./spec/emoji/regex_spec.cr", source)
end

create_source_file
